[mgr]
prepend_keymap = [
    { on = "q", run = "close", desc = "Close the current tab, or quit if it is last tab" },
    { on = "c", run = "plugin chmod", desc = "Chmod on selected files" },
    { on = "`", run = "shell \"$SHELL\" --block --confirm", desc = "Open shell here" },
    { on = "f", run = "plugin jump-to-char", desc = "Jump to Char" },
    { on = "F", run = "plugin smart-filter", desc = "Smart Filter" },
    { on = "R", run = "shell -- dragon-drop -x -i -T %h", desc = "Drag Files" },
]
