[mgr]
prepend_keymap = [
    { on = "q", run = "close", desc = "Close the current tab, or quit if it is last tab" },
    { on = "c", run = "plugin chmod", desc = "Chmod on selected files" },
    { on = "\\", run = "plugin --sync hide-preview", desc = "Toggle preview pane" },
    { on = "`", run = "shell \"$SHELL\" --block --confirm", desc = "Open shell here" },
    { on = "C", run = "plugin ouch --args=zip", desc = "Compress with ouch" },
    { on = "f", run = "plugin jump-to-char", desc = "Jump to Char" },
    { on = "F", run = "plugin smart-filter", desc = "Smart Filter" },
]
