general {
	lock_cmd = pidof hyprlock || hyprlock
	before_sleep_cmd = loginctl lock-session
	after_sleep_cmd = hyprctl dispatch "hl.dsp.dpms({ action = 'enable' })"
}

listener {
	timeout = 300
	on-timeout = brightnessctl -s set 90% ; hyprctl hyprsunset gamma 90
	on-resume = brightnessctl -r ; hyprctl hyprsunset gamma 100
}

listener {
	timeout = 301
	on-timeout = brightnessctl -s set 80% ; hyprctl hyprsunset gamma 80
	on-resume = brightnessctl -r ; hyprctl hyprsunset gamma 100
}

listener {
	timeout = 302
	on-timeout = brightnessctl -s set 70% ; hyprctl hyprsunset gamma 70
	on-resume = brightnessctl -r ; hyprctl hyprsunset gamma 100
}

listener {
	timeout = 303
	on-timeout = brightnessctl -s set 50% ; hyprctl hyprsunset gamma 50
	on-resume = brightnessctl -r ; hyprctl hyprsunset gamma 100
}

listener {
	timeout = 304
	on-timeout = brightnessctl -s set 25% ; hyprctl hyprsunset gamma 25
	on-resume = brightnessctl -r ; hyprctl hyprsunset gamma 100
}

listener {
	timeout = 305
	on-timeout = brightnessctl -s set 1% ; hyprctl hyprsunset gamma 10
	on-resume = brightnessctl -r ; hyprctl hyprsunset gamma 100
}

listener {
	timeout = 310
	on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
	on-resume = brightnessctl -rd rgb:kbd_backlight
}

listener {
	timeout = 360
	on-timeout = loginctl lock-session
}

listener {
	timeout = 420
	on-timeout = hyprctl dispatch "hl.dsp.dpms({ action = 'disable' })"
	on-resume = hyprctl dispatch "hl.dsp.dpms({ action = 'enable' })" && brightnessctl -r
}
