keys:
    # - &espresso
  - &gram age1lz46eqnfuu6uyxnzj28me0um8auumeg36mv3hlzd5ms7ms7muejshtg2mv
  - &installer age12w6w86sxqwgp9pvm9r5l42fszjcj7td8zj868ju7v2mz2tskrgzswvzaf8
  - &magrathea age1f0fdr7u3gnlmuvqdpegplcw5kffscy89pjqqwjft4xp59mfzhdms8hm8c4
  - &mjolnir age1yefxgkjq8xlrcthtpksy3ejeajnmtv76cc4ltcq6ysjs8xmqzyqst8jezm
  # - &oolong
  # - &serenity
  # - &matshkas_espresso
  - &matt_gram age19q60y4usv9rffpjwvhv0atj0m997mkqcm39wcrnfdp3exmh68ewsvdkrgx
  - &matt_magrathea age1g99w2utuz4d2psf5y2pjld5ezhuuhjwvynmp5j762qw7znu6wvhsq8mwhf
  - &matt_mjolnir age1um585taq4ea4dayx23mjkqehqty2f76n23yk39v7q4c24zyfjq0qqmxl20
  # - &matshkas_oolong
  # - &matt_serenity
creation_rules:
  - path_regex: secrets.yaml
    key_groups:
    - age:
      - *gram
      - *installer
      - *magrathea
      - *mjolnir
      - *matt_gram
      - *matt_magrathea
      - *matt_mjolnir
  - path_regex: users/secrets-matshkas.yaml
    key_groups:
    - age:
      - *gram
      - *installer
      - *magrathea
      - *mjolnir
  - path_regex: users/secrets-matt.yaml
    key_groups:
    - age:
      - *gram
      - *installer
      - *magrathea
      - *mjolnir
      - *matt_gram
      - *matt_magrathea
      - *matt_mjolnir
