keys:
  - &espresso age17245y07suqz07qaxwtn49sp9syug97zlqdd4v5hw3l8q3g2wmalsm3q3y7
  - &gram age1lz46eqnfuu6uyxnzj28me0um8auumeg36mv3hlzd5ms7ms7muejshtg2mv
  - &hofud age1sk540ajmcdwyx2avqxjkck5z34kyu3pus9nwfeqrf5wuxf00fq0q4a0fff
  - &installer age12w6w86sxqwgp9pvm9r5l42fszjcj7td8zj868ju7v2mz2tskrgzswvzaf8
  - &magrathea age1f0fdr7u3gnlmuvqdpegplcw5kffscy89pjqqwjft4xp59mfzhdms8hm8c4
  - &mjolnir age1yefxgkjq8xlrcthtpksy3ejeajnmtv76cc4ltcq6ysjs8xmqzyqst8jezm
  - &oolong age18qkc05k8dmz2f7gnga3x5k77axavn9gh42c4x6u072kdtt4053vqpe7smk
  # - &serenity
  - &matt_gram age19q60y4usv9rffpjwvhv0atj0m997mkqcm39wcrnfdp3exmh68ewsvdkrgx
  - &matt_hofud age1gzz0mn42whyp8t23dmzcgvv2tzutgqy26grl42vx5mghrs67v42qcpp3xx
  - &matt_magrathea age1g99w2utuz4d2psf5y2pjld5ezhuuhjwvynmp5j762qw7znu6wvhsq8mwhf
  - &matt_mjolnir age1um585taq4ea4dayx23mjkqehqty2f76n23yk39v7q4c24zyfjq0qqmxl20
creation_rules:
  - path_regex: secrets.yaml
    key_groups:
    - age:
      - *espresso
      - *gram
      - *hofud
      - *installer
      - *magrathea
      - *mjolnir
      - *oolong
      - *matt_gram
      - *matt_hofud
      - *matt_magrathea
      - *matt_mjolnir
