keys:
  # - &gram  
  - &hofud age1sk540ajmcdwyx2avqxjkck5z34kyu3pus9nwfeqrf5wuxf00fq0q4a0fff
  - &installer age12w6w86sxqwgp9pvm9r5l42fszjcj7td8zj868ju7v2mz2tskrgzswvzaf8
  - &magrathea age1f0fdr7u3gnlmuvqdpegplcw5kffscy89pjqqwjft4xp59mfzhdms8hm8c4
  - &mjolnir age1yefxgkjq8xlrcthtpksy3ejeajnmtv76cc4ltcq6ysjs8xmqzyqst8jezm
  # - &matt_gram 
  - &matt_hofud age1gzz0mn42whyp8t23dmzcgvv2tzutgqy26grl42vx5mghrs67v42qcpp3xx
  - &matt_magrathea age1g99w2utuz4d2psf5y2pjld5ezhuuhjwvynmp5j762qw7znu6wvhsq8mwhf
  - &matt_mjolnir age1um585taq4ea4dayx23mjkqehqty2f76n23yk39v7q4c24zyfjq0qqmxl20
creation_rules:
  - path_regex: secrets.yaml
    key_groups:
    - age:
      # - *gram
      - *hofud
      - *installer
      - *magrathea
      - *mjolnir
      # - *matt_gram
      - *matt_hofud
      - *matt_magrathea
      - *matt_mjolnir
