[general]
fullscreen = false
resize = { mode="smart" }
corner-roundness = 16
initial-tool = "brush"
copy-command = "wl-copy"
annotation-size-factor = 1
output-filename = "$HOME/Pictures/Screenshots/%Y%m%d%H%M%S.png"
save-after-copy = false
default-hide-toolbars = false
focus-toggles-toolbars = false
default-fill-shapes = false
primary-highlighter = "block"
disable-notifications = false
actions-on-right-click = []
actions-on-enter = ["save-to-clipboard"]
actions-on-escape = ["exit"]
action-on-enter = "save-to-clipboard"
right-click-copy = false
no-window-decoration = true
brush-smooth-history-size = 20
pan-step-size = 50.0
zoom-factor = 1
text-move-length = 50.0
input-scale = 2.0

[keybinds]
pointer = "p"
crop = "c"
brush = "b"
line = "l"
arrow = "a"
rectangle = "r"
ellipse = "e"
text = "t"
marker = "m"
blur = "u"
highlight = "h"

[font]
family = "Recursive Sans Casual Static"
style = "Regular"
fallback = [
	"Inter",
	"JuliaMono",
	"Liberation Sans",
	"Liberation Serif",
	"Liga Rec Mono Custom",
	"Maple Mono NF"
]

[color-palette]
palette = [
	"#e78284",
	"#ef9f76",
	"#e5c890",
	"#a6d189",
	"#81c8be",
	"#99d1db",
	"#85c1dc",
	"#8caaee",
	"#ca9ee6",
	"#f4b8e4",
	"#c6d0f5",
	"#232634"
]

custom = [
]
