# Config
# Settings            -->
#-----------------------
# vim:fdm=marker:fdl=0:foldmarker=-->,<--

font: Maple Mono NF 11
background: "#232634d8"
border: "#81c8be"
separator: "  ➜  "
border_width: 1
corner_r: 10
padding: 15
rows_per_column: 8
column_padding: 100

anchor: bottom
margin_bottom: 75

inhibit_compositor_keyboard_shortcuts: true

auto_kbd_layout: true

menu:
#--<--------------------
# Hyprland Controls   -->
#-----------------------

  - key: "`"
    desc: "Hyprland Window Controls"
    submenu:
      - key: "h"
        desc: "Focus Window Left"
        cmd: hyprctl dispatch "hl.dsp.focus({direction='l'})
      - key: "j"
        desc: "Focus Window Down"
        cmd: hyprctl dispatch "hl.dsp.focus({direction='d'})
      - key: "k"
        desc: "Focus Window Up"
        cmd: hyprctl dispatch "hl.dsp.focus({direction='u'})
      - key: "l"
        desc: "Focus Window Right"
        cmd: hyprctl dispatch "hl.dsp.focus({direction='r'})
      - key: "H"
        desc: "Move Window Left"
        cmd: hyprctl dispatch "hl.dsp.focus({direction='l'})
      - key: "J"
        desc: "Move Window Down"
        cmd: hyprctl dispatch "hl.dsp.focus({direction='d'})
      - key: "K"
        desc: "Move Window Up"
        cmd: hyprctl dispatch "hl.dsp.focus({direction='u'})
      - key: "L"
        desc: "Move Window Right"
        cmd: hyprctl dispatch "hl.dsp.focus({direction='r'})
      - key: "Tab"
        desc: "Switch Windows"
        cmd: hyprctl dispatch "hl.dsp.window.cycle_next()" && hyprctl dispatch "hl.dsp.window.bring_to_top()"
      - key: "f"
        desc: "Toggle Fullscreen"
        cmd: hyprctl dispatch "hl.dsp.window.fullscreen()"
      - key: "o"
        desc: "Toggle Pseudotile"
        cmd: hyprctl dispatch "hl.dsp.window.pseudo()"
      - key: "w"
        desc: "Toggle Floating"
        cmd: hyprctl dispatch "hl.dsp.window.float({action = 'toggle'})"
      - key: "x"
        desc: "Close Window"
        cmd: hyprctl dispatch "hl.dsp.window.close()"
      - key: "backslash"
        desc: "Reload Hyprland and Waybar"
        cmd: systemctl --user restart waybar && hyprctl reload

#--<--------------------
# Resize Menu         -->
#-----------------------

  - key: "R"
    desc: "[R]esize Menu"
    submenu:
    - key: ["Left", "h"]
      desc: "Width  ---"
      cmd: hyprctl dispatch "hl.dsp.window.resize({x=-240, y=0, relative=true})"
      keep_open: true
    - key: ["Down", "j"]
      desc: "Height ---"
      cmd: hyprctl dispatch "hl.dsp.window.resize({x=0, y=190, relative=true})"
      keep_open: true
    - key: ["Up", "k"]
      desc: "Height +++"
      cmd: hyprctl dispatch "hl.dsp.window.resize({x=0, y=-190, relative=true})"
      keep_open: true
    - key: ["Right", "l"]
      desc: "Width  +++"
      cmd: hyprctl dispatch "hl.dsp.window.resize({x=240, y=0, relative=true})"
      keep_open: true
    - key: ["Alt+Left", "Alt+h"]
      desc: "Width  --"
      cmd: hyprctl dispatch "hl.dsp.window.resize({x=-24, y=0, relative=true})"
      keep_open: true
    - key: ["Alt+Down", "Alt+j"]
      desc: "Height --"
      cmd: hyprctl dispatch "hl.dsp.window.resize({x=0, y=19, relative=true})"
      keep_open: true
    - key: ["Alt+Up", "Alt+k"]
      desc: "Height ++"
      cmd: hyprctl dispatch "hl.dsp.window.resize({x=0, y=-19, relative=true})"
      keep_open: true
    - key: ["Alt+Right", "Alt+l"]
      desc: "Width  ++"
      cmd: hyprctl dispatch "hl.dsp.window.resize({x=24, y=0, relative=true})"
      keep_open: true
    - key: ["Ctrl+Left", "Ctrl+h"]
      desc: "Width  -"
      cmd: hyprctl dispatch "hl.dsp.window.resize({x=-1, y=0, relative=true})"
      keep_open: true
    - key: ["Ctrl+Down", "Ctrl+j"]
      desc: "Height -"
      cmd: hyprctl dispatch "hl.dsp.window.resize({x=0, y=1, relative=true})"
      keep_open: true
    - key: ["Ctrl+Up", "Ctrl+k"]
      desc: "Height +"
      cmd: hyprctl dispatch "hl.dsp.window.resize({x=0, y=-1, relative=true})"
      keep_open: true
    - key: ["Ctrl+Right", "Ctrl+l"]
      desc: "Width  +"
      cmd: hyprctl dispatch "hl.dsp.window.resize({x=1, y=0, relative=true})"
      keep_open: true

#--<--------------------
# Notifications       -->
#-----------------------

  - key: "n"
    desc: "[N]otification Menu"
    submenu:
      - key: "x"
        desc: "Close"
        cmd: dunstctl close
      - key: "a"
        desc: "Close [A]ll"
        cmd: dunstctl close-all
      - key: "p"
        desc: "History [P]op"
        cmd: dunstctl history-pop
      - key: "c"
        desc: "[C]ontext"
        cmd: dunstctl context
      - key: "BackSpace"
        desc: "Previous Menu"
        cmd: wlr-which-key

#--<--------------------
# Printscreen Menu    -->
#-----------------------

  - key: "Print"
    desc: "[Print]screen Menu"
    submenu:
      - key: "s"
        desc: "Entire [S]creen"
        cmd: grim $(xdg-user-dir PICTURES)/Screenshots/$(date +"%Y%m%d%H%M%S.png")
      - key: "a"
        desc: "Catpure [A]rea"
        cmd: slurp | grim -g - - | magick - -shave 1x1 PNG:- | satty -f - --copy-command wl-copy -o "~/Pictures/Screenshots/%Y%m%d%H%M%S.png"
      - key: "o"
        desc: "[O]ptical Character Recognition"
        cmd: slurp | grim -g - - | tesseract - - | wl-copy
      - key: "r"
        desc: "[R]ecord Screen"
        cmd: /nix/config/scripts/screenRecord.sh
      - key: "BackSpace"
        desc: "Previous Menu"
        cmd: wlr-which-key

#--<--------------------
# Power Menu          -->
#-----------------------

  - key: "p"
    desc: "[P]ower Menu"
    submenu:
      - key: "l"
        desc: "[L]ock Screen"
        cmd: hyprlock
      - key: "r"
        desc: "[R]eboot"
        cmd: reboot
      - key: "s"
        desc: "[S]leep"
        cmd: systemctl suspend
      - key: "o"
        desc: "Power [O]ff"
        cmd: poweroff
      - key: "BackSpace"
        desc: "Previous Menu"
        cmd: wlr-which-key

#--<--------------------
# Top Level Launchers -->
#-----------------------

  - key: "b"
    desc: "[B]top System Monitor"
    cmd: kitty --class "float-large" btop
  - key: "c"
    desc: "[C]alculator"
    cmd: kitty --class "float-small" qalc
  - key: "e"
    desc: "Fil[e] Manager"
    cmd: kitty --class "float-large" yazi
  - key: "g"
    desc: "Play Media in MPV"
    cmd: /nix/config/scripts/yt-dlp.sh
  - key: "m"
    desc: "Password [M]anager"
    cmd: keepmenu
  - key: "q"
    desc: "Terminal"
    cmd: kitty
  - key: "r"
    desc: "[R]un Application"
    cmd: fuzzel
  - key: "u"
    desc: "Color Picker"
    cmd: hyprpicker -a
  - key: "v"
    desc: "'Paste' using wtype"
    cmd: wtype $(cliphist list | fuzzel -d | cliphist decode)
