$vrr = 1
$gaps_in = 9
$gaps_out = 20

$d2width = 1880
$d2height = 1015

monitor=HDMI-A-1, 1920x1080@60, 0x0, 1

exec-once=wayland-push-to-talk-fix -k 'grave' -n 'grave' /dev/input/by-id/usb-04d9_daskeyboard-event-kbd

# Launch terminal apps
bind=SUPER SHIFT, q, exec, [float; size 1000 608; center;] kitty
bind=SUPER CTRL, q, exec, [pseudo; size 1000 608; center;] kitty
bind=SUPER, y, exec, [float; size 1000 608; center;] kitty yazi
bind=SUPER, c, exec, [float; size 420 323; center;] kitty qalc
