$vrr = 0
$gaps_in = 8
$gaps_out = 16

monitor=eDP-1, 2256x1504@60, auto, 1.175000

# Laptop lid
bindl= , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"
bindl= , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, 2256x1504@60, auto, 1.175000"

# Laptop tent mode
bind=SUPER, t, exec, hyprctl keyword monitor eDP-1,preferred,auto,1.175000,transform,2
bind=SUPER SHIFT, t, exec, hyprctl keyword monitor eDP-1,preferred,auto,1.175000,transform,0

# Toggle laptop keyboard
bind=SUPER, b, exec, bash /nix/config/scripts/toggle-keyboard.sh

# Launch terminal apps
bind=SUPER SHIFT, q, exec, [float; size 1319 1031; center;] kitty
bind=SUPER CTRL, q, exec, [pseudo; size 1319 1031; center;] kitty
bind=SUPER, y, exec, [float; size 996 599; center;] kitty yazi
bind=SUPER, c, exec, [float; size 420 318; center;] kitty qalc
