[mgr]
prepend_keymap = [
	{ on = "`", run = "shell \"$SHELL\" --block --confirm", desc = "Open shell here" },
	{ on = "c", run = "plugin chmod", desc = "Chmod on selected files" },
	{ on = "C", run = "plugin ouch", desc = "Compress with ouch" },
	{ on = "f", run = "plugin jump-to-char", desc = "Jump to Char" },
	{ on = "F", run = "plugin smart-filter", desc = "Smart Filter" },
	{ on = "l", run = "plugin smart-enter", desc = "Enter the child directory or open file" },
	{ on = [ "M", "d" ], run = "plugin mount", desc = "Mount drives interface" },
	{ on = [ "M", "s" ], run = "plugin sshfs -- menu", desc = "Mount SSHFS" },
	{ on = "q", run = "close", desc = "Close the current tab, or quit if it is last tab" },
	{ on = [ "y", "c" ], run = "copy path", desc = "Copy file URL" },
	{ on = [ "y", "d" ], run = "copy dirname", desc = "Copy directory URL" },
	{ on = [ "y", "f" ], run = "copy filename", desc = "Copy filename" },
	{ on = [ "y", "n" ], run = "copy name_without_ext", desc = "Copy filename without extension" },
	{ on = [ "y", "y" ], run = "yank", desc = "Yank selected files (copy)" },
]
