[[language]]
name = "go"
auto-format = true
indent = { tab-width = 3, unit = "\t" }

[[language]]
name = "html"
auto-format = true
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "lua"
auto-format = true
indent = { tab-width = 3, unit = "\t" }

[[language]]
name = "nix"
auto-format = true
indent = { tab-width = 4, unit = " " }

[[language]]
name = "yaml"
auto-format = true
indent = { tab-width = 2, unit = " " }

[[language]]
name = "templ"
auto-format = true
indent = { tab-width = 2, unit = "\t" }
