general {
	hide_cursor = true
	ignore_empty_input = true
}

animations {
	enabled = true
	bezier = linear, 1, 1, 0, 0
	animation = fadeIn, 1, 5, linear
	animation = fadeOut, 1, 5, linear
	animation = inputFieldDots, 1, 2, linear
}

auth {
	fingerprint:enabled = true
}

background {
	monitor =
	path = screenshot
	blur_passes = 3
	crossfade_time = 2
}

label {
	monitor =
	text = cmd[update:1000] echo "<b>$(date +"%k:%M")</b>"
	color = rgb(c6d0f5)
	font_size = 50
	font_family = Maple Mono NF
	position = -130, -100
	halign = right
	valign = top
	shadow_passes = 2
}

label {
	monitor =
	text = cmd[update:1000] echo "$(date +"%A, %B %e %Y")"
	color = rgb(c6d0f5)
	font_size = 20
	font_family = Maple Mono NF
	position = -130, -200
	halign = right
	valign = top
	shadow_passes = 2
}

image {
	monitor =
	path = $HOME/Pictures/Saved/profile.png
	size = 300
	border_color = rgb(85c1dc)
	rounding = -1
	position = 0, 75
	halign = center
	valign = center
	shadow_passes = 2
}

input-field {
	monitor =
	size = 420, 48
	outline_thickness = 3
	dots_size = 0.2
	dots_spacing = 0.4
	dots_center = true
	outer_color = rgba(85c1dcee) rgba(81c8beee)
	inner_color = rgba(303446ee)
	font_color = rgba(a5adceaa)
	font_family = Maple Mono NF
	fade_on_empty = false
	placeholder_text = <i>󰌾 Logged in as </i>$USER
	hide_input = false
	check_color = rgba(99d1dbee)
	fail_color = rgba(e78284ee)
	fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
	capslock_color = rgb(e5c890)
	position = 0, -200
	halign = center
	valign = center
	shadow_passes = 2
}
