include frappe.conf

# System
allow_remote_control yes
listen_on unix:/tmp/kitty
enable_audio_bell no
linux_display_server wayland

# Fonts
font_family family="Maple Mono NF" postscript_name=MapleMono-NF-Regular features="+calt +cv02 +cv03 +cv05 +cv07 +cv31 +cv38 +cv40 +cv62 +ss03 +ss07 +ss08 +ss11 +zero"
bold_font auto
italic_font auto
bold_italic_font auto
font_size 10.6
disable_ligatures never

# Cursor
cursor_shape beam
cursor_beam_thickness 1.8

# Tab Bar
tab_bar_style powerline
tab_powerline_style round
tab_title_max_length 15

# URLs
detect_urls yes
open_url_with default
url_style curly

# Integrations
editor nvim
scrollback_pager nvim -u NONE -R -M -c 'lua require("kitty-scrollback")(INPUT_LINE_NUMBER, CURSOR_LINE, CURSOR_COLUMN)' -
scrollback_lines 5000
shell fish
shell_integration enabled

# Layouts
enabled_layouts splits,stack

# Keybindings
clear_all_shortcuts yes

# General
map alt+\          load_config_file
map alt+0          change_font_size all 0
map alt+equal      change_font_size all +1.0
map alt+minus      change_font_size all -1.0
map alt+plus       change_font_size all +8.0
map alt+underscore change_font_size all -8.0

# Scrollback
map alt+u          scroll_page_up
map alt+d          scroll_page_down
map alt+e          show_scrollback

# Hints
map alt+shift+u kitten hints --type=url

# Tabs
map alt+t          new_tab
map alt+.          next_tab
map alt+,          previous_tab
map alt+shift+t    set_tab_title
map alt+shift+.    move_tab_forward
map alt+shift+,    move_tab_backward

# Windows
map alt+f          toggle_layout stack
map alt+n          launch --cwd=current --location=hsplit --bias 50
map alt+shift+n    launch --cwd=current --location=hsplit --bias -20
map alt+v          launch --cwd=current --location=vsplit --bias 50
map alt+shift+v    launch --cwd=current --location=vsplit --bias -20
map alt+x          close_window
map alt+h          neighboring_window left
map alt+j          neighboring_window down
map alt+k          neighboring_window up
map alt+l          neighboring_window right
map alt+shift+h    move_window left
map alt+shift+j    move_window down
map alt+shift+k    move_window up
map alt+shift+l    move_window right
map alt+left       kitten relative_resize.py left
map alt+down       kitten relative_resize.py down
map alt+up         kitten relative_resize.py up
map alt+right      kitten relative_resize.py right
